In [1]:
import numpy as np

In [2]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[1]

1

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr=arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
# : selects all the elements in the array
# set all the elements of array to 99
slice_of_arr[:]=99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [18]:
'''
    Although I changed slice_of_arr the chsnges will also reflect
    in the other array since there is only one copy of array
'''
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [19]:
'''
    to get a copy of the array  
'''
arr_copy=arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [21]:
arr_copy[1]=1500
arr_copy

array([  99, 1500,   99,   99,   99,   99,    6,    7,    8,    9,   10])

In [22]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [28]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [29]:
arr_2d[1]

array([20, 25, 30])